-- 프로그래머스 코딩테스트 연습 오랜 기간 보호한 동물
SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS LEFT 
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY INS.DATETIME LIMIT 3